[versions]
agp = "9.4.0"
kotlin = "2.4.20"
ksp = "2.3.12"
room = "2.8.5"
lifecycle = "2.11.0"
webkit = "1.17.0"

[libraries]
androidx-core-ktx = "androidx.core:core-ktx:1.19.0"
androidx-activity-compose = "androidx.activity:activity-compose:1.13.0"
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-datastore-preferences = "androidx.datastore:datastore-preferences:1.2.1"
androidx-graphics-shapes = "androidx.graphics:graphics-shapes:1.1.0"
androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
compose-bom = "androidx.compose:compose-bom:2026.09.00"
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material3 = "androidx.compose.material3:material3:1.5.0-alpha28"
compose-material-icons = "androidx.compose.material:material-icons-extended:1.7.8"
kotlinx-coroutines-android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.11.0"
junit = "junit:junit:4.13.2"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
